[[language]]
name = "nix"
auto-format = true
formatter = { command = "nixfmt" }
language-servers = [ "nil" ]

[language-server.nil.config.formatting]
command = ["nixfmt"]

[language-server.nil.config.nix.flake]
autoArchive = true
autoEvalInputs = false

[language-server.nixd]
command = "nixd"

[language-server.nixd.config.nixd.formatting]
command = ["nixfmt"]

[language-server.nixd.config.nixd.nixpkgs]
expr = "let flake = builtins.getFlake \"/var/home/cyrene/.config/home-manager\"; in import flake.inputs.nixpkgs { system = builtins.currentSystem; }"

[[language]]
name = "json"
auto-format = true
formatter = { command = "biome", args = ["format", "--stdin-file-path", "%{buffer_name}"] }
language-servers = [ "vscode-json-language-server" ]

[[language]]
name = "json"
language-servers = [ { name = "vscode-json-language-server", except-features = [ "format" ] }, "biome" ]

[[language]]
name = "dockerfile"
auto-format = true
