# mpv keybindings
WHEEL_UP add volume 2
WHEEL_DOWN add volume -2

RIGHT seek 5
LEFT seek -5

Ctrl+UP add sub-scale +0.1
Ctrl+DOWN add sub-scale -0.1
Ctrl+RIGHT add sub-delay +0.1
Ctrl+LEFT add sub-delay -0.1

j cycle sub
J cycle sub down
v cycle sub-visibility

s screenshot
S screenshot video