# mpv configuration
vo=gpu-next,gpu
hwdec=auto
sub-auto=fuzzy
slang=zh,chi,eng,en
alang=jpn,eng,en
osd-font=JetBrains Mono
sub-font-size=40
sub-scale=0.8

# YouTube profile
[youtube]
profile-cond = string.find(path or '', 'youtube') ~= nil
cache = yes
cache-secs = 60
ytdl-format = bestvideo+bestaudio
hwdec = auto
demuxer-max-bytes = 200M
demuxer-max-back-bytes = 100M